package:
  name: pelican
  version: "3.6.3"

source:
  fn: pelican-3.6.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pelican/pelican-3.6.3.tar.gz
  md5: ee4110fc60af26459f4e2f7c9fa9cdd5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pelican = pelican:main
    #
    # Would create an entry point called pelican that calls pelican.main()

    - pelican = pelican:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - feedgenerator >=1.6
    - jinja2 >=2.7
    - pygments
    - docutils
    - pytz >=0a
    - blinker
    - unidecode
    - six >=1.4
    - python-dateutil

  run:
    - python
    - feedgenerator >=1.6
    - jinja2 >=2.7
    - pygments
    - docutils
    - pytz >=0a
    - blinker
    - unidecode
    - six >=1.4
    - python-dateutil

test:
  # Python imports
  imports:
    - pelican
    - pelican.tools

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pelican --help
    - pelican-import --help
    - pelican-quickstart --help
    - pelican-themes --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://getpelican.com/
  license: GNU Affero General Public License v3
  summary: 'A tool to generate a static blog from reStructuredText or Markdown input files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
