package:
  name: pelican-gist
  version: "0.3.3"

source:
  fn: pelican-gist-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pelican-gist/pelican-gist-0.3.3.tar.gz
  md5: 9cac3d2e25d4f796b236544e93b11711
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pelican-gist = pelican-gist:main
    #
    # Would create an entry point called pelican-gist that calls pelican-gist.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.2.0

  run:
    - python
    - requests >=2.2.0

test:
  # Python imports
  imports:
    - pelican_gist

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock >=1.0.1
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/streeter/pelican-gist
  license: MIT License
  summary: 'Easily embed GitHub Gists in your Pelican articles.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
